<?php defined('include_only') or die('No direct script access.');

return [

    // Database Connection Info
    'db_host'     => '',
    'db_port'     => null, // null will use defaults (MySQL = 3306; PostgreSQL = 5432). If your database is running on a non-standard port, set this to the appropriate integer value.
    'db_name'     => '',
    'db_username' => '',
    'db_password' => '',
    'RDBMS'       => 'mysql', // 'mysql' or 'pgsql'
    'db_schema'   => null, // PostgreSQL schema name; null defaults to 'public' (not applicable to MySQL)

    // Domain Info
    'domain' => 'change-me.com', // eg "my-domain.com"
    'default_email' => 'no-reply@change-me.com', // system transactional e-mails come from this address

    'timezone' => 'America/New_York',

    'send_email' => true, // if false, transactional e-mails generated by the system will be supressed

    'use_p13n' => false, // allow for multiple personalization versions of a given content block (required for i18n)
    // To use i18n, set this to an ARRAY of allowed URL segments.
    'i18n_segments' => null, // null, false, or an empty array if not using internationalization (i18n) URLs. 

    // OPTIONAL Mailgun credentials (see www.mailgun.com for more information)
    // install library via composer
    'MAILGUN_Enabled' => false,
    'MAILGUN_Base_Url' => '',
    'MAILGUN_API_Key' => '',

    // OPTIONAL Twilio credentials (see www.twilio.com for more information)
    // required for SMS-based two factor authentication
    // install library via composer
    'TWILIO_Enabled' => false,
    'TWILIO_SMS_Number' => '',
    'TWILIO_AccountSid' => '',
    'TWILIO_AuthToken' => '',

    // OPTIONAL 3rd party API for image compression; required for automatic image optimization on upload and recommended for general use to reduce bandwidth and speed up load times
    // see https://tinify.com/developers for more information and pricing details (free tier allows for 500 compressions per month)
    // tinify api library is installed via composer
    'TINYPNG_Enabled' => false,
    'TINYPNG_API_Key' => '',
    'TINYPNG_Max_Width' => 1920, // max width for uploaded images; set to false for no resizing

    // Path to encryption key
    // default location is humblee/configuration/crypto/key.php, but you can generate your key and place it elsewhere if desired; just update the path accordingly. Key file should return a string of the encryption key, which must be exactly 32 characters in length.    
    'crypto_key' => 'humblee/configuration/crypto/key.php'
];
