<?php

return array(

    // MySQL Connection Info    
    'db_host' => '',
    'db_name' => '',
    'db_username' => '',
    'db_password' => '',

    // Domain Info
    'domain' => 'change-me.com', // eg "my-domain.com"
    'default_email' => 'no-reply@change-me.com', // system transactional e-mails come from this address
    
    'timezone' => 'America/New_York',
    
    'send_email' => true, // if false, transactional e-mails generated by the system will be supressed

    // OPTIONAL Mailgun credentials (see www.mailgun.com for more information)
    'MAILGUN_Enabled' => false,
    'MAILGUN_Base_Url' => '',
    'MAILGUN_API_Key' => '',

    // OPTIONAL Twilio credentials (see www.twilio.com for more information)
    'TWILIO_Enabled' => false,
    'TWILIO_SMS_Number' => '',
    'TWILIO_AccountSid' => '',
    'TWILIO_AuthToken' => ''
);