<?php defined('include_only') or die('No direct script access.');

return array(

    // MySQL Connection Info
    'db_host' => '',
    'db_name' => '',
    'db_username' => '',
    'db_password' => '',

    // Domain Info
    'domain' => 'change-me.com', // eg "my-domain.com"
    'default_email' => 'no-reply@change-me.com', // system transactional e-mails come from this address

    'timezone' => 'America/New_York',

    'send_email' => true, // if false, transactional e-mails generated by the system will be supressed

    'use_p13n' => false, // allow for multiple personalization versions of a given content block (required for i18n)
    'i18n_segments' => false, // false if not using internationalization (i18n) URLs. To use i18n, set this to an ARRAY of allowed URL segments.

    // OPTIONAL Mailgun credentials (see www.mailgun.com for more information)
    // install library via composer
    'MAILGUN_Enabled' => false,
    'MAILGUN_Base_Url' => '',
    'MAILGUN_API_Key' => '',

    // OPTIONAL Twilio credentials (see www.twilio.com for more information)
    // required for SMS-based two factor authentication
    // install library via composer
    'TWILIO_Enabled' => false,
    'TWILIO_SMS_Number' => '',
    'TWILIO_AccountSid' => '',
    'TWILIO_AuthToken' => '',

    // OPTIONAL tinyPNG credentials (see tinypng.com/developers)
    // install tinify library via composer
    'TINYPNG_Enabled' => false,
    'TINYPNG_API_Key' => '',

    // Path to encryption key
    'crypto_key' => 'humblee/configuration/crypto/key.php'
);